theme = "gruvbox_dark_hard"

[editor]
bufferline = "multiple"
cursorline = true
true-color = true
rulers = [120]
auto-format = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
newline = "all"
tab = "all"

[editor.whitespace.characters]
tab = ">"
tabpad = "—"
nbsp = "⍽"
newline = "⏎"
space = "·"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.lsp]
enable = true
display-inlay-hints = true
display-messages = true

[keys.normal]
A-L = ":format"
C-A-left = "jump_backward"
C-A-right = "jump_forward"
A-right = "goto_next_buffer"
A-left = "goto_previous_buffer"
C-b = "goto_definition"
C-d = ["extend_line_below", "yank_joined_to_clipboard", "paste_clipboard_after", "goto_line_start"]
C-s = [":w"]
C-q = [":q"]
C-F = "global_search"
C-f = "search"
'C-/' = "toggle_comments"
tab = "indent"
S-tab = "unindent"
'del' = "delete_selection"
S-F10 = [":wa", ":sh zellij run -d right -- run_project.sh %{filename} &> /dev/null || true"]
C-9 = [":wa", ":sh zellij run -d right -- build_project.sh %{filename} &> /dev/null || true"]
C-e = "buffer_picker"
# A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
C-w = ":buffer-close"

[keys.insert]
A-L = ":format"
C-s = ["normal_mode", ":w"]
'C-/' = "toggle_comments"
S-tab = "unindent"
C-space = "completion"

[keys.select]
# A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
